config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount RailsAdmin::Engine => '/admin_2', as: 'rails_admin'

  resources :designs, :only => [:index, :show] do
    member do
      get :renderer
      get :similar
      get :furniture_recommendations
      post :replace_furniture
      post :save_to_my_designs
    end
  end

  resources :rooms, :only => [:new, :index, :create, :update] do
    collection do
      post :create_with_layout
    end

    member do
      get :layouts
      post :save_design
    end

    resources :custom_designs, :only => [:index, :show] do
      member do
        get :similar
        post :replace_furniture
      end
    end
  end

  resources :moodboards, :only => [:index, :show, :update] do
    member do
      post :publish
      post :unpublish
      post :archive
    end
  end

  resources :furnitures do
    collection do
      get :all
    end

    member do
      get :loader
      get :renderer
      get :perspective
      put :update_dimensions
      put :update_lights
      put :remove_views
    end

    resources :furniture_views, only: [:create, :destroy]
  end

  get '/inspirations', to: "inspirations#index"

  get '/layout_engine/catalog_configs', to: 'layout_engine#catalog_configs'
  get '/layout_engine/manage', to: 'layout_engine#manage', :as => 'manage_layout_engine'
  post '/layout_engine/get_placements', to: 'layout_engine#get_placements'
  post '/layout_engine/save', to: 'layout_engine#save', :as => 'save_layout_engine'

  get '/sessions/user', to: 'sessions#user'
  post '/sessions/request_otp', to: 'sessions#request_otp'
  post '/sessions/login', to: 'sessions#login'
  delete '/sessions/logout', to: 'sessions#logout', :as => 'logout'

  get '/looks', to: 'designs#looks'
  get '/furnitures/:id', to: "designs#furniture"
  get '/rooms/:room_id/layouts/:layout_id/designs/:design_index/views/:view_index', to: 'designs#view'
  get '/rooms/:room_id/layouts/:layout_id/next_design/:view_index', to: 'designs#next'

  get '/rooms/select', to: 'rooms#templates'
  get '/rooms/:id', to: "rooms#show"
  post '/designs/:id/views/:view_index', to: "designs#view"
  post '/designs/next', to: "designs#next"

  get '/chrode/furnitures/:id/renderer', to: "furnitures#chrode_renderer"
  get '/chrode/furnitures/status', to: "furnitures#chrode_status"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#show'
end

app/models/moodboard.rb
# == Schema Information
#
# Table name: moodboards
#
#  id            :integer          not null, primary key
#  room_category :string
#  created_at    :datetime
#  updated_at    :datetime
#

class Moodboard < ApplicationRecord
  cattr_accessor :design_options

  has_many :moodboard_category_collections, dependent: :destroy
  has_many :category_collections, through: :moodboard_category_collections

  REQUIRED_CATEGORIES = {
    RoomCategory::LIVING_ROOM => [
      FurnitureCategory::SOFA,
      FurnitureCategory::DINING_SET
    ]
  }

  validates :room_category, inclusion: { in: RoomCategory.values }

  def complete?
    required_categories = REQUIRED_CATEGORIES[self.room_category]
    (required_categories - self.category_collections.map(&:category).uniq).empty?
  end

  def self.all_design_options
    if !@@design_options
      @@design_options = []

      Moodboard.includes(:category_collections => :furnitures).each do |moodboard|
        @@design_options += moodboard.design_options
      end
    end

    return @@design_options
  end

  def design_options
    furniture_tree = self.category_collections.map {|c| c.furnitures.to_a }
    furniture_products = furniture_tree[0].product(*furniture_tree[1..-1])

    _values = []

    furniture_products.each do |furnitures|
      _map = {}

      furnitures.each do |furniture|
        _map[furniture.category] = furniture
      end

      _values << _map
    end

    return _values
  end

  # def design_options_new
  #   _val = {}

  #   self.furnitures.each do |furniture|
  #     matching_furnitures = Furniture.all_furnitures.select { |f|
  #         f.category == furniture.category &&
  #         (f.colors & furniture.colors).any? &&
  #         (f.styles & furniture.colors).any?
  #     }
  #     _val = matching_furnitures.map{ |mf| x = {}; x[furniture.category.to_sym] = mf.id}}
  #   end

  #   return _val[0].product(_val[1..-1])
  # end

end

app/controllers/moodboards_controller.rb
require 'layout_engine_manager'

class MoodboardsController < ApplicationController
  def index
    @is_draft = params[:published] == 'false'
    @moodboards = @is_draft ? Moodboard.draft : Moodboard.published
  end

  def show
    respond_to do |format|
      format.json do
        @moodboard = Moodboard.find(params[:id])

        render json: MoodboardSerializer.new(@moodboard).attributes
      end

      format.html do
        @moodboard = Moodboard.find(params[:id])
        super_categories = @moodboard.required_super_categories_map.map {|e| e[0] }

        # So, get the category list from the super category list which Grobr understands.
        categories = super_categories.map {|super_category|
          LEM::FURNISH_CONFIG[@moodboard.room_type][:categories].select {|category, details| details[:status] != 'new' && details[:super_category] == super_category }.keys
        }.flatten
        variant_ids = categories.map {|category|
          LEM::FURNISH_CONFIG[@moodboard.room_type][:categories][category][:variants]
        }.flatten.map {|v| v[:id] }

        furnitures_url = Services::GROBR + "/furnitures.json?boxs_variant_ids=#{variant_ids.join(',')}"
        response = Faraday.get(furnitures_url)

        # Convert them back to super category so that the moodboard can understand it.
        super_category_furnitures = JSON.parse(response.body).group_by {|f|
          category = LEM.get_category_of(@moodboard.room_type, f['boxs_variant_id'])
          LEM.get_super_category_of(@moodboard.room_type, category)[:name]
        }

        furnitures_data = super_category_furnitures.map {|super_category, furnitures|
          [
            super_category,
            furnitures.group_by {|furniture| furniture['id'] }.map {|id, entries| [ id, entries[0]] }.to_h
          ]
        }.to_h

        @furnitures_data = furnitures_data
      end
    end
  end

  def update
    @moodboard = Moodboard.find(params[:id])

    furniture_map = []

    params[:furniture_ids_by_super_category].each do |super_category, furniture_ids|
      furniture_map << { super_category: super_category, furniture_ids: furniture_ids || [] }
    end

    @moodboard.update furniture_map: furniture_map

    if @moodboard.valid?
      render nothing: true
    else
      render status: 400, text: @moodboard.errors.full_messages
    end
  end

  def publish
    @moodboard = Moodboard.find(params[:id])
    @moodboard.publish!

    if @moodboard.valid?
      flash[:success] = "Moodboard published successfully."
      redirect_to moodboards_path(published: true)
    else
      flash[:alert] = @moodboard.errors.full_messages.join(". ")
      redirect_to moodboards_path
    end
  end

  def unpublish
    @moodboard = Moodboard.find(params[:id])
    @moodboard.unpublish!
    redirect_to moodboards_path(published: false)
  end

  def archive
    @moodboard = Moodboard.find(params[:id])
    @furniture.archive!
    redirect_to moodboards_path(published: false)
  end
end

app/views/moodboards/index.html.erb
<%= stylesheet_link_tag 'boxs_app/moodboard' %>

<div class='page_wrapper'>
  <div class='page_title'>
    <div class='title_text'>
        Moodboards (<%= @is_draft ? 'Draft' : 'Published' %>) (<%= @moodboards.size %>)
    </div>
  </div>
  <div class='page_content'>
    <%= link_to 'Published', moodboards_path %>
    <%= link_to 'Draft', moodboards_path(published: false) %>
    <div class="moodboards_index">
      <% @moodboards.each_with_index do |moodboard, index| %>
        <div class="item <%= 'alt' if index % 2 == 1 %>">
          <div class='furnitures'>
            <% moodboard.furniture_map_with_details.each do |entry| %>
              <% entry['furnitures'].each_with_index do |furniture_info, index| %>
                <% if furniture_info %>
                  <div class='furniture'>
                    <div class='image_wrapper'>
                      <%= image_tag furniture_info['image_urls'][0] %>
                    </div>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
          <div class='actions'>
            <span>
              #<%= moodboard.id %>
            </span>
            <span>
              <% if moodboard.draft? %>
                  <%= link_to "Publish", publish_moodboard_path(moodboard), :method => :post, :class => 'btn btn-small btn-primary', confirm: "Are you sure you want to publish? This can't be undone" %>
              <% else %>
                <%= link_to "Archive", archive_moodboard_path(moodboard), :method => :post, :class => 'btn btn-small btn-primary', confirm: "Are you sure you want to archive? This can't be undone" %>
              <% end %>
            </span>
            <%= link_to 'Edit', moodboard_path(moodboard), target: '_blank', :class => 'btn btn-small btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= javascript_include_tag 'boxs_app/moodboard.js' %>

app/views/moodboards/show.html.erb
<%= stylesheet_link_tag 'boxs_app/moodboard' %>

<div class='page_wrapper' ng-controller="MoodboardController" ng-init="init(<%= @moodboard.id %>)">
  <div class='page_title'>
    <div class='title_text'>
        Moodboard #<%= @moodboard.id %>
    </div>
    <div>
      <%= link_to 'All Moodboards', moodboards_path %>
    </div>
  </div>
  <div class='page_content'>
    <div class='moodboard'>
      <div class='wrapper'>
        <div class='mapping_grid'>
          <div class='grid_wrapper'>
            <div ng-repeat="categoryEntry in moodboard.required_super_categories_map"
                 class='category_entry'
                 ng-class="{ alt: $index % 2 === 0 }">
              <div ng-repeat="index in [].constructor(categoryEntry[1]) track by $index"
                   ng-class="{ active: isActiveSlot(categoryEntry[0], $index) }"
                   class='rank_slot'>
                <div class='slot_value'>
                  <img ng-src="{{ furnituresBySuperCategory[categoryEntry[0]][moodboard.furniture_ids_by_super_category[categoryEntry[0]][$index]]['image_urls'][0] }}"
                       class='image'
                       ng-if="moodboard.furniture_ids_by_super_category[categoryEntry[0]][$index]"
                     />
                  <div ng-if="!moodboard.furniture_ids_by_super_category[categoryEntry[0]][$index]"
                       class='empty'>
                    Blank
                  </div>
                </div>
                <div class='slot_action'>
                  <button ng-click="deselectSlot(categoryEntry[0], $index)"
                          ng-show="isActiveSlot(categoryEntry[0], $index)"
                          class='btn btn-small btn-primary'
                          >
                    Close
                  </button>
                  <button ng-click="selectSlot(categoryEntry[0], $index)"
                          ng-hide="isActiveSlot(categoryEntry[0], $index)"
                          ng-disabled="isAnySlotSelected()"
                          class='btn btn-small btn-secondary'>
                    Assign
                  </button>
                </div>
                <div class='category'>
                  {{ categoryEntry[0] }}
                </div>
                <span ng-if="categoryEntry[1] > 1">
                  #{{ $index + 1 }}
                </span>
              </div>
            </div>
          </div>
          <div class='save'>
            <button ng-click="save()" class='btn btn-primary'>
              Save
            </button>
          </div>
        </div>
        <div class='furniture_selector'>
          <div ng-show="!isAnySlotSelected()">
            Select a slot
          </div>
          <div ng-repeat="(superCategory, furnitures) in furnituresBySuperCategory"
               ng-if="superCategory === slot.superCategory"
               class='category_wrapper'>
            <div ng-repeat="(id, furniture) in furnitures"
                 ng-click="assignSlot(id)"
                 class='furniture_item'>
              <img ng-src="{{ furniture.image_urls[0] }}" />
            </div>
          </div>
        </div>
      </div>
      <div>
        <h3>Sample Designs</h3>
        <div class='rooms'>
          <ul>
            <% @moodboard.sample_rooms.each do |room| %>
              <li>
                Room #<%= link_to room.id, room_path(room) %>
              </li>
            <% end %>
            <li>
              <a href='#' ng-click="newDesign()">
                Create New Room
              </a>
            </li>
          </ul>
        </div>
        <div class='designs'>
          <% @moodboard.sample_designs.each do |design| %>
            <%= link_to design_path(design) do %>
              <div>
                <%= !design.is_private? ? 'Featured' : 'Not Featured' %>
              </div>
              <%= image_tag design.primary_render.image.small.url, target: '_blank' %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/ng-template" id="newRoom.html">
  <%= render partial: 'rooms/new' %>
</script>

<script type='text/javascript'>
  const baseData = {
    furnitures: <%= raw(@furnitures_data.to_json) %>
  }
</script>

<%= javascript_include_tag 'boxs_app/moodboard' %>
<%= javascript_include_tag 'boxs_app/new_room' %>