config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount RailsAdmin::Engine => '/admin_2', as: 'rails_admin'

  resources :designs, :only => [:index, :show] do
    member do
      get :renderer
      get :similar
      get :furniture_recommendations
      post :replace_furniture
      post :save_to_my_designs
    end
  end

  resources :rooms, :only => [:new, :index, :create, :update] do
    collection do
      post :create_with_layout
    end

    member do
      get :layouts
      post :save_design
    end

    resources :custom_designs, :only => [:index, :show] do
      member do
        get :similar
        post :replace_furniture
      end
    end
  end

  resources :moodboards, :only => [:index, :show, :update] do
    member do
      post :publish
      post :unpublish
      post :archive
    end
  end

  resources :furnitures do
    collection do
      get :all
    end

    member do
      get :loader
      get :renderer
      get :perspective
      put :update_dimensions
      put :update_lights
      put :remove_views
    end

    resources :furniture_views, only: [:create, :destroy]
  end

  get '/inspirations', to: "inspirations#index"

  get '/layout_engine/catalog_configs', to: 'layout_engine#catalog_configs'
  get '/layout_engine/manage', to: 'layout_engine#manage', :as => 'manage_layout_engine'
  post '/layout_engine/get_placements', to: 'layout_engine#get_placements'
  post '/layout_engine/save', to: 'layout_engine#save', :as => 'save_layout_engine'

  get '/sessions/user', to: 'sessions#user'
  post '/sessions/request_otp', to: 'sessions#request_otp'
  post '/sessions/login', to: 'sessions#login'
  delete '/sessions/logout', to: 'sessions#logout', :as => 'logout'

  get '/looks', to: 'designs#looks'
  get '/furnitures/:id', to: "designs#furniture"
  get '/rooms/:room_id/layouts/:layout_id/designs/:design_index/views/:view_index', to: 'designs#view'
  get '/rooms/:room_id/layouts/:layout_id/next_design/:view_index', to: 'designs#next'

  get '/rooms/select', to: 'rooms#templates'
  get '/rooms/:id', to: "rooms#show"
  post '/designs/:id/views/:view_index', to: "designs#view"
  post '/designs/next', to: "designs#next"

  get '/chrode/furnitures/:id/renderer', to: "furnitures#chrode_renderer"
  get '/chrode/furnitures/status', to: "furnitures#chrode_status"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#show'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <%= display_meta_tags %>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400&display=swap" rel="stylesheet">
    <link rel="canonical" href="<%= url_for(subdomain: nil, only_path: false, protocol: 'http') %>"/>
    <link rel="icon" type="image/png" href="<%= image_path('boxs-favicon-16x16.png') %>" sizes="16x16"/>
    <link rel="icon" type="image/png" href="<%= image_path('boxs-favicon-32x32.png') %>" sizes="32x32"/>

    <%= stylesheet_link_tag "boxs_app/application", :media => "all" %>
    <%= javascript_include_tag "boxs_app/application" %>
    <%= csrf_meta_tags %>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-133950150-5"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-133950150-5');
    </script>

    <% if track_in_full_story? %>
      <script>
      window['_fs_debug'] = false;
      window['_fs_host'] = 'fullstory.com';
      window['_fs_script'] = 'edge.fullstory.com/s/fs.js';
      window['_fs_org'] = '12S696';
      window['_fs_namespace'] = 'FS';
      (function(m,n,e,t,l,o,g,y){
          if (e in m) {if(m.console && m.console.log) { m.console.log('FullStory namespace conflict. Please set window["_fs_namespace"].');} return;}
          g=m[e]=function(a,b,s){g.q?g.q.push([a,b,s]):g._api(a,b,s);};g.q=[];
          o=n.createElement(t);o.async=1;o.crossOrigin='anonymous';o.src='https://'+_fs_script;
          y=n.getElementsByTagName(t)[0];y.parentNode.insertBefore(o,y);
          g.identify=function(i,v,s){g(l,{uid:i},s);if(v)g(l,v,s)};g.setUserVars=function(v,s){g(l,v,s)};g.event=function(i,v,s){g('event',{n:i,p:v},s)};
          g.anonymize=function(){g.identify(!!0)};
          g.shutdown=function(){g("rec",!1)};g.restart=function(){g("rec",!0)};
          g.log = function(a,b){g("log",[a,b])};
          g.consent=function(a){g("consent",!arguments.length||a)};
          g.identifyAccount=function(i,v){o='account';v=v||{};v.acctId=i;g(o,v)};
          g.clearUserCookie=function(){};
          g.setVars=function(n, p){g('setVars',[n,p]);};
          g._w={};y='XMLHttpRequest';g._w[y]=m[y];y='fetch';g._w[y]=m[y];
          if(m[y])m[y]=function(){return g._w[y].apply(this,arguments)};
          g._v="1.3.0";
      })(window,document,window['_fs_namespace'],'script','user');
      </script>
    <% end %>
  </head>
  <body ng-app="boxsApp" ng-cloak ng-strict-di ng-init="initApp()">
    <% if flash.any? && !@local_flash %>
      <div class="notice" ng-hide="hideFlash">
        <% flash.each do |key, message| %>
          <div class="alert alert-<%= key %>">
            <%= message %>
            <a href ng-click="hideFlash = true" class="close_link">
              <span class="fa fa-times"></span>
            </a>
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="main_navbar" ng-hide="skipNav">
      <div uib-dropdown class='mobile_screen mobile_menu'>
        <div uib-dropdown-toggle>
          <span class="fa fa-list icon"></span>
        </div>
      </div>
      <div class="main_logo">
        <%= link_to root_path do %>
          <%= image_tag 'boxs_logo.png', :class => 'logo' %>
        <% end %>
      </div>
      <div class='filler'></div>
      <div class="r">
        <div class='item login' ng-if="!currentUser">
          <button ng-click="login()" class='btn btn-bordered'>
            <span class='fa fa-user'></span>
            <span>Login</span>
          </button>
        </div>
        <div class='item' ng-if="currentUser">
          <%= link_to 'My Rooms', rooms_path %>
        </div>
        <div class='item' ng-if="currentUser">
          <span class='name'>{{ currentUser.name }}</span>
          <%= link_to logout_path, method: :delete do %>
            <span class='fa fa-power-off'></span>
          <% end %>
        </div>
      </div>
    </div>
    <div class="main_wrapper">
      <div class="main_content">
        <%= yield %>
      </div>
    </div>
    <script type="text/ng-template" id="info-modal">
      <div class='modal-content-wrapper'>
        {{ message }}
      </div>
      <div class='modal-actions'>
        <div class='actions'>
          <button class='btn btn-primary' ng-click='modal.close()'>Close</button>
        </div>
      </div>
    </script>
    <script type="text/ng-template" id="progress_modal">
      <div class="modal-content-wrapper">
        <div class='loader'>
          <%= image_tag 'loading_wedges.gif' %>
        </div>
        <div class='message'>
          {{ messageProgressBar.message }}
        </div>
        <uib-progressbar value="messageProgressBar.progress">
        </uib-progressbar>
      </div>
    </script>
    <script type="text/ng-template" id="newRoom.html">
      <%= render partial: 'rooms/new' %>
    </script>
  </body>
</html>

<%= render partial: 'sessions/login' %>

app/views/layouts/site_layout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <%= display_meta_tags %>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400&display=swap" rel="stylesheet">
    <link rel="canonical" href="<%= url_for(subdomain: nil, only_path: false, protocol: 'http') %>"/>
    <link rel="icon" type="image/png" href="<%= image_path('boxs-favicon-16x16.png') %>" sizes="16x16"/>
    <link rel="icon" type="image/png" href="<%= image_path('boxs-favicon-32x32.png') %>" sizes="32x32"/>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-133950150-5"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-133950150-5');
    </script>
  </head>
  <body ng-app="boxsApp" ng-cloak ng-strict-di ng-init="initApp()">
    <% if flash.any? && !@local_flash %>
      <div class="notice" ng-hide="hideFlash">
        <% flash.each do |key, message| %>
          <div class="alert alert-<%= key %>">
            <%= message %>
            <a href ng-click="hideFlash = true" class="close_link">
              <span class="fa fa-times"></span>
            </a>
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="main_navbar" sticky ng-hide="skipNav">
      <div class="main_logo">
        <%= link_to root_path do %>
          <%= image_tag 'boxs_logo.png', :class => 'logo' %>
        <% end %>
      </div>
      <div class='filler'></div>
      <div class="r">
        <div class='item login' ng-if="!currentUser">
          <button ng-click="login()" class='btn btn-bordered'>
            <span class='fa fa-user'></span>
            <span>Login</span>
          </button>
        </div>
        <div class='item' ng-if="currentUser">
          <%= link_to 'My Rooms', rooms_path %>
        </div>
        <div class='item' ng-if="currentUser">
          {{ currentUser.name }}
          <%= link_to logout_path, method: :delete do %>
            <span class='fa fa-power-off'></span>
          <% end %>
        </div>
      </div>
    </div>
    <div class="main_wrapper">
      <div class="main_content">
        <%= yield %>
      </div>
    </div>
    <script type="text/ng-template" id="info-modal">
      <div class='modal-content-wrapper'>
        {{ message }}
      </div>
      <div class='modal-actions'>
        <div class='actions'>
          <button class='btn btn-primary' ng-click='modal.close()'>Close</button>
        </div>
      </div>
    </script>
  </body>
</html>

<%= render partial: 'sessions/login' %>